// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guestbook.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestbookEntry = `-- name: CreateGuestbookEntry :one
INSERT INTO guestbook_entries (page_user_id, author_user_id, body)
VALUES ($1, $2, $3)
RETURNING id, page_user_id, author_user_id, body, state, created_at
`

type CreateGuestbookEntryParams struct {
	PageUserID   uuid.UUID
	AuthorUserID uuid.UUID
	Body         string
}

func (q *Queries) CreateGuestbookEntry(ctx context.Context, arg CreateGuestbookEntryParams) (GuestbookEntry, error) {
	row := q.db.QueryRow(ctx, createGuestbookEntry, arg.PageUserID, arg.AuthorUserID, arg.Body)
	var i GuestbookEntry
	err := row.Scan(
		&i.ID,
		&i.PageUserID,
		&i.AuthorUserID,
		&i.Body,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const listVisibleGuestbookEntries = `-- name: ListVisibleGuestbookEntries :many
SELECT e.id, e.body, e.created_at, u.handle AS author_handle
FROM guestbook_entries e
JOIN users u ON u.id = e.author_user_id
WHERE e.page_user_id = $1 AND e.state = 'visible'
ORDER BY e.created_at DESC
LIMIT $2
`

type ListVisibleGuestbookEntriesParams struct {
	PageUserID uuid.UUID
	Lim        int32
}

type ListVisibleGuestbookEntriesRow struct {
	ID           uuid.UUID
	Body         string
	CreatedAt    pgtype.Timestamptz
	AuthorHandle *string
}

// Joins users for the author's handle so one query renders the whole list,
// rather than a lookup per entry.
func (q *Queries) ListVisibleGuestbookEntries(ctx context.Context, arg ListVisibleGuestbookEntriesParams) ([]ListVisibleGuestbookEntriesRow, error) {
	rows, err := q.db.Query(ctx, listVisibleGuestbookEntries, arg.PageUserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisibleGuestbookEntriesRow
	for rows.Next() {
		var i ListVisibleGuestbookEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
