// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_tokens.sql

package store

import (
	"context"
)

const consumeLoginToken = `-- name: ConsumeLoginToken :one
UPDATE login_tokens
SET    consumed_at = now()
WHERE  token_hash = $1
  AND  consumed_at IS NULL
  AND  expires_at > now()
RETURNING email
`

// Spends a token and reports who it belongs to. Single-use is enforced here, in
// one statement, and not by reading the row and then updating it: two requests
// arriving together would both pass the read and both proceed. The UPDATE takes
// a row lock, so exactly one of them matches consumed_at IS NULL.
//
// No row means the token does not exist, has expired, or has already been spent.
// The caller cannot tell which, and should not: reporting the difference tells
// an attacker which of their guesses were once real tokens.
func (q *Queries) ConsumeLoginToken(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, consumeLoginToken, tokenHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const createLoginToken = `-- name: CreateLoginToken :exec
INSERT INTO login_tokens (token_hash, email, expires_at)
VALUES ($1, $2, now() + make_interval(secs => $3::double precision))
`

type CreateLoginTokenParams struct {
	TokenHash  []byte
	Email      string
	TtlSeconds float64
}

// expires_at is computed by the database rather than passed in. The expiry check
// in ConsumeLoginToken reads the database clock, so the deadline has to come
// from that same clock: taken from the application host instead, any skew
// between the two silently lengthens or shortens every token's life.
func (q *Queries) CreateLoginToken(ctx context.Context, arg CreateLoginTokenParams) error {
	_, err := q.db.Exec(ctx, createLoginToken, arg.TokenHash, arg.Email, arg.TtlSeconds)
	return err
}

const invalidateLoginTokensForEmail = `-- name: InvalidateLoginTokensForEmail :exec
UPDATE login_tokens
SET    consumed_at = now()
WHERE  email = $1
  AND  consumed_at IS NULL
`

// Requesting a new link retires the outstanding ones, so at most one link for an
// address works at a time. Cheap, and it bounds what an attacker gains from a
// mailbox they can read but not control.
func (q *Queries) InvalidateLoginTokensForEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, invalidateLoginTokensForEmail, email)
	return err
}
