// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LoginToken struct {
	ID         uuid.UUID
	TokenHash  []byte
	Email      string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

type Session struct {
	ID          uuid.UUID
	SessionHash []byte
	UserID      uuid.UUID
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Email     string
	Handle    *string
	State     string
	Tier      string
	Locale    string
	CreatedAt pgtype.Timestamptz
}
