// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moods.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getMoodByUserID = `-- name: GetMoodByUserID :one
SELECT user_id, mood_key, note, updated_at FROM moods WHERE user_id = $1
`

func (q *Queries) GetMoodByUserID(ctx context.Context, userID uuid.UUID) (Mood, error) {
	row := q.db.QueryRow(ctx, getMoodByUserID, userID)
	var i Mood
	err := row.Scan(
		&i.UserID,
		&i.MoodKey,
		&i.Note,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMoodHistory = `-- name: InsertMoodHistory :exec
INSERT INTO mood_history (user_id, mood_key, note) VALUES ($1, $2, $3)
`

type InsertMoodHistoryParams struct {
	UserID  uuid.UUID
	MoodKey string
	Note    *string
}

// Append-only, one row per change. Nothing reads this yet; it exists so a
// future "tu mes en moods" view is a query, not a migration.
func (q *Queries) InsertMoodHistory(ctx context.Context, arg InsertMoodHistoryParams) error {
	_, err := q.db.Exec(ctx, insertMoodHistory, arg.UserID, arg.MoodKey, arg.Note)
	return err
}

const upsertMood = `-- name: UpsertMood :one
INSERT INTO moods (user_id, mood_key, note, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE
    SET mood_key = excluded.mood_key, note = excluded.note, updated_at = now()
RETURNING user_id, mood_key, note, updated_at
`

type UpsertMoodParams struct {
	UserID  uuid.UUID
	MoodKey string
	Note    *string
}

// The mood a page shows is a single current value, never a history of rows
// to pick the latest from — the same DO UPDATE shape as UpsertUserByEmail,
// for the same reason: one row per user, always.
func (q *Queries) UpsertMood(ctx context.Context, arg UpsertMoodParams) (Mood, error) {
	row := q.db.QueryRow(ctx, upsertMood, arg.UserID, arg.MoodKey, arg.Note)
	var i Mood
	err := row.Scan(
		&i.UserID,
		&i.MoodKey,
		&i.Note,
		&i.UpdatedAt,
	)
	return i, err
}
