// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (session_hash, user_id, expires_at)
VALUES ($1, $2, now() + make_interval(secs => $3::double precision))
`

type CreateSessionParams struct {
	SessionHash []byte
	UserID      uuid.UUID
	TtlSeconds  float64
}

// expires_at is computed by the database for the same reason as
// CreateLoginToken: the expiry check in LookupSession reads the database
// clock, so the deadline has to come from that clock too.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.SessionHash, arg.UserID, arg.TtlSeconds)
	return err
}

const lookupSession = `-- name: LookupSession :one
SELECT user_id FROM sessions
WHERE  session_hash = $1
  AND  revoked_at IS NULL
  AND  expires_at > now()
`

// No row means the session does not exist, has expired, or was revoked. The
// caller cannot tell which, for the same reason ConsumeLoginToken merges its
// three causes: the difference is only useful to whoever is guessing.
func (q *Queries) LookupSession(ctx context.Context, sessionHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lookupSession, sessionHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET    revoked_at = now()
WHERE  session_hash = $1
  AND  revoked_at IS NULL
`

// Revoking twice is not an error: logout should look like it worked whether
// or not the session was still live, so the caller never needs to check
// rows-affected before clearing the cookie.
func (q *Queries) RevokeSession(ctx context.Context, sessionHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, sessionHash)
	return err
}
