// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, handle, state, tier, locale, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.State,
		&i.Tier,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (lower(email)) DO UPDATE SET email = users.email
RETURNING id, email, handle, state, tier, locale, created_at
`

// Returns the account for an email, creating it on first use. Login is a signup
// when the account does not exist yet; there is no separate registration step
// to keep in sync.
//
// The DO UPDATE writes the value back unchanged on purpose. DO NOTHING would be
// the honest expression of the intent, but it returns no row on conflict, and
// this query must return the existing account.
func (q *Queries) UpsertUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.State,
		&i.Tier,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}
